import 'package:flutter/material.dart';

const iconOptions = [
  Icons.ac_unit_rounded,
  Icons.access_alarm_rounded,
  Icons.accessibility_new_rounded,
  Icons.account_balance_rounded,
  Icons.account_balance_wallet_rounded,
  Icons.adf_scanner_rounded,
  Icons.adobe_rounded,
  Icons.agriculture_rounded,
  Icons.airplane_ticket_outlined,
  Icons.airplanemode_on_rounded,
  Icons.airplay_rounded,
  Icons.airport_shuttle_rounded,
  Icons.all_inbox_rounded,
  Icons.all_inclusive_rounded,
  Icons.alternate_email_rounded,
  Icons.anchor_rounded,
  Icons.android_rounded,
  Icons.animation_rounded,
  Icons.apartment_rounded,
  Icons.apple_rounded,
  Icons.approval_rounded,
  Icons.architecture_rounded,
  Icons.archive_rounded,
  Icons.area_chart_rounded,
  Icons.article_rounded,
  Icons.assignment_rounded,
  Icons.assistant_photo_rounded,
  Icons.attach_file_rounded,
  Icons.attach_money_rounded,
  Icons.attractions_rounded,
  Icons.audiotrack_rounded,
  Icons.auto_awesome_rounded,
  Icons.auto_stories_rounded,
];