// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP8N5Sw01kUaMrjoV1h5nKb9rCEbN4OK4',
    appId: '1:776547417872:web:6f163264ea834e36846f95',
    messagingSenderId: '776547417872',
    projectId: 'cashfy-app-17cb4',
    authDomain: 'cashfy-app-17cb4.firebaseapp.com',
    storageBucket: 'cashfy-app-17cb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQD3Apt7syIo_TZrOwY0uvKH-cTLUQ2g',
    appId: '1:776547417872:android:62f629ea512d5200846f95',
    messagingSenderId: '776547417872',
    projectId: 'cashfy-app-17cb4',
    storageBucket: 'cashfy-app-17cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvnYSjrzzDpMZJ925Yysg8kX9mgQei27A',
    appId: '1:776547417872:ios:97a6731c7db23673846f95',
    messagingSenderId: '776547417872',
    projectId: 'cashfy-app-17cb4',
    storageBucket: 'cashfy-app-17cb4.appspot.com',
    iosClientId: '776547417872-efldgtqe9acslde3g1lhkbm7f3nngvdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.financialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvnYSjrzzDpMZJ925Yysg8kX9mgQei27A',
    appId: '1:776547417872:ios:97a6731c7db23673846f95',
    messagingSenderId: '776547417872',
    projectId: 'cashfy-app-17cb4',
    storageBucket: 'cashfy-app-17cb4.appspot.com',
    iosClientId: '776547417872-efldgtqe9acslde3g1lhkbm7f3nngvdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.financialApp',
  );
}
